syntax = "proto3";

package tieba;

import "Abstract.proto";
import "Agree.proto";
import "AlaLiveInfo.proto";
import "Media.proto";
import "PbContent.proto";
import "SimpleForum.proto";
import "User.proto";
import "VideoInfo.proto";
import "ZhiBoInfoTW.proto";

message ThreadInfo {
  int64 id = 1;
  int64 threadId = 2;
  string title = 3;
  int32 replyNum = 4;
  int32 viewNum = 5;
  int32 lastTimeInt = 7;
  int32 isTop = 9;
  int32 isGood = 10;
  User author = 18;
  repeated Abstract _abstract = 21;
  repeated Media media = 22;
  int64 forumId = 27;
  string forumName = 28;
  int64 firstPostId = 40;
  int32 createTime = 45;
  int64 authorId = 56;
  ZhiBoInfoTW twzhibo_info = 72;
  optional VideoInfo videoInfo = 79;
  optional AlaLiveInfo ala_info = 113;
  int32 agreeNum = 124;
  Agree agree = 126;
  repeated PbContent firstPostContent = 142;
  SimpleForum forumInfo = 155;
  int32 isDeleted = 181;
}
