syntax = "proto3";

package tieba.pbPage;

import "Error.proto";
import "Anti.proto";
import "Page.proto";
import "Post.proto";
import "SimpleForum.proto";
import "ThreadInfo.proto";
import "User.proto";

message PbPageResponseData {
  tieba.SimpleForum forum = 2;
  tieba.Page page = 3;
  tieba.Anti anti = 4;
  repeated tieba.Post post_list = 6;
  tieba.ThreadInfo thread = 8;
  repeated tieba.User user_list = 13;
  tieba.Post first_floor_post = 38;
}

message PbPageResponse {
  tieba.Error error = 1;
  PbPageResponseData data = 2;
}
